version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - revive
    - sloglint
    - unconvert
    - unparam
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kitos7/scratchy
